# Generated by Django 4.2 on 2025-06-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
