# Generated by Django 4.2 on 2025-06-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_verificationcode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='authenticat_user_id_35f8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['email', 'code'], name='authenticat_email_b9d56d_idx'),
        ),
    ]
