# Generated by Django 4.2 on 2025-06-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_verificationcode_email_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='verificationcode',
            name='authenticat_email_b9d56d_idx',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['email'], name='authenticat_email_120a88_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['created_at'], name='authenticat_created_4ee39e_idx'),
        ),
    ]
